// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Morrow$ReMorrow = require("./morrow.bs.js");

var bookString = Morrow$ReMorrow.Read[/* file */0]("save-the-princess.json");

var exampleBook = Morrow$ReMorrow.Parser[/* parseBook */2](Json.parseOrRaise(bookString));

console.log(exampleBook[/* title */0]);

exports.bookString = bookString;
exports.exampleBook = exampleBook;
/* bookString Not a pure module */
