// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Express = require("bs-express/src/Express.js");
var Process = require("process");
var Morrow$ReMorrow = require("./morrow.bs.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

var bookString = Morrow$ReMorrow.Read[/* file */0]("save-the-princess.json");

var exampleBook = Morrow$ReMorrow.recreateBookFromString(bookString);

var CreatedBook = /* module */[/* book */exampleBook];

var CurrentBook = Morrow$ReMorrow.MakeBook(CreatedBook);

console.log(CurrentBook[/* title */1]);

var startPage = Curry._1(CurrentBook[/* pageByName */3], "introduction");

console.log(Morrow$ReMorrow.Page[/* pageContent */1](startPage));

Curry._1(CurrentBook[/* printChoices */6], startPage);

console.log(Morrow$ReMorrow.Page[/* pageContent */1](Curry._1(CurrentBook[/* takeChoice */5], Morrow$ReMorrow.Page[/* choiceByName */3]("next", startPage))));

var app = Express.express(/* () */0);

function onListen(e) {
  var exit = 0;
  var val;
  try {
    val = e;
    exit = 1;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      console.log(exn[1]);
      Process.exit(1);
      return /* () */0;
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    console.log("Listening at http://127.0.0.1:3001");
    return /* () */0;
  }
  
}

function makeSuccessJson(param) {
  var json = { };
  json["success"] = true;
  return json;
}

Express.App[/* get */4](app, "/", Express.Middleware[/* from */5]((function (next, req) {
            var partial_arg = makeSuccessJson(/* () */0);
            var partial_arg$1 = Express.Response[/* sendJson */3];
            return (function (param) {
                return partial_arg$1(partial_arg, param);
              });
          })));

Express.App[/* listen */19](app, 3001, onListen, /* () */0);

var port = 3001;

exports.bookString = bookString;
exports.exampleBook = exampleBook;
exports.CreatedBook = CreatedBook;
exports.CurrentBook = CurrentBook;
exports.startPage = startPage;
exports.app = app;
exports.port = port;
exports.onListen = onListen;
exports.makeSuccessJson = makeSuccessJson;
/* bookString Not a pure module */
