// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var List = require("bs-platform/lib/js/list.js");
var Path = require("path");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function pageName(page) {
  return page[/* name */0];
}

function pageContent(page) {
  return page[/* content */1];
}

function pageChoices(page) {
  return page[/* choices */2];
}

function choiceByName(choiceName) {
  return (function (param) {
      return List.find((function (choice) {
                    return choice[/* name */0] === choiceName;
                  }), param);
    });
}

var Page = /* module */[
  /* pageName */pageName,
  /* pageContent */pageContent,
  /* pageChoices */pageChoices,
  /* choiceByName */choiceByName
];

function choiceName(choice) {
  return choice[/* name */0];
}

function page(choice) {
  return choice[/* page */1];
}

var Choice = /* module */[
  /* choiceName */choiceName,
  /* page */page
];

function MakeBook(Item) {
  var book = Item[/* book */0];
  var title = Item[/* book */0][/* title */0];
  var length = List.length(Item[/* book */0][/* pages */1]);
  var pageByName = function (name) {
    return List.find((function (page) {
                  return name === page[/* name */0];
                }), book[/* pages */1]);
  };
  var pageContents = function (name) {
    return pageByName(name)[/* content */1];
  };
  var takeChoice = function (choice) {
    return pageByName(choice[/* page */1]);
  };
  var printBook = function (param) {
    var book = Item[/* book */0];
    console.log("Title: " + book[/* title */0]);
    console.log("Book Length: " + String(length));
    console.log("Ratings: Some Rating");
    return /* () */0;
  };
  return /* module */[
          /* book */book,
          /* title */title,
          /* length */length,
          /* pageByName */pageByName,
          /* pageContents */pageContents,
          /* takeChoice */takeChoice,
          /* printBook */printBook
        ];
}

function parseChoice(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* pageName */Json_decode.field("page", Json_decode.string, json)
        ];
}

function parsePage(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* content */Json_decode.field("content", Json_decode.string, json),
          /* choicesData */Json_decode.field("choices", (function (param) {
                  return Json_decode.list(parseChoice, param);
                }), json)
        ];
}

function parseBook(json) {
  return /* record */[
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* pagesData */Json_decode.field("pages", (function (param) {
                  return Json_decode.list(parsePage, param);
                }), json)
        ];
}

var Parser = /* module */[
  /* parseChoice */parseChoice,
  /* parsePage */parsePage,
  /* parseBook */parseBook
];

function file(fileName) {
  return Fs.readFileSync(Path.join(fileName), "utf8");
}

function fileJson(fileName) {
  return Fs.readFileSync(Path.join(fileName), "utf8");
}

var Read = /* module */[
  /* file */file,
  /* fileJson */fileJson
];

function recreateBook(data) {
  return /* record */[
          /* title */data[/* title */0],
          /* pages */List.map((function (pageData) {
                  return /* record */[
                          /* name */pageData[/* name */0],
                          /* content */pageData[/* content */1],
                          /* choices */List.map((function (choiceData) {
                                  return /* record */[
                                          /* name */choiceData[/* name */0],
                                          /* page */choiceData[/* pageName */1]
                                        ];
                                }), pageData[/* choicesData */2])
                        ];
                }), data[/* pagesData */1])
        ];
}

exports.Page = Page;
exports.Choice = Choice;
exports.MakeBook = MakeBook;
exports.Parser = Parser;
exports.Read = Read;
exports.recreateBook = recreateBook;
/* fs Not a pure module */
