// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function userInput(param) {
  return Pervasives.read_line(/* () */0);
}

function promptUser(string) {
  console.log(string);
  return Pervasives.read_line(/* () */0);
}

exports.userInput = userInput;
exports.promptUser = promptUser;
/* No side effect */
